version: '3.1'

services:
  feed-service:
    image: feed-img:v1
    container_name: feed-service
    restart: unless-stopped
    volumes:
      - gvm_plugins:/var/lib/openvas/plugins
      - gvm_notus:/var/lib/notus
      - gvm_log:/var/log/feedsync

  openvas-service:
    image: scanner-img:v1
    container_name: openvas-service
    privileged: true
    cap_add:
      - NET_ADMIN    # Allows OpenVAS to perform network-related tasks.
      - NET_RAW      # Allows OpenVAS to use raw sockets, essential for scanning.
#    network_mode: host
    depends_on:
      - feed-service
    ports:
      - "3001:3001"
    volumes:
      - gvm_plugins:/var/lib/openvas/plugins
      - gvm_notus:/var/lib/notus

volumes:
  gvm_plugins:
  gvm_notus:
  gvm_log:
