apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gvm-plugins-pvc
  namespace: gvm
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gvm-notus-pvc
  namespace: gvm
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gvm-log-pvc
  namespace: gvm
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi