apiVersion: v1
kind: ServiceAccount
metadata:
  name: openvas
  namespace: gvm
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openvas-discovery
  namespace: gvm
rules:
  - apiGroups: [""]
    resources: ["pods","endpoints","services"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openvas-discovery
  namespace: gvm
subjects:
  - kind: ServiceAccount
    name: openvas
    namespace: gvm
roleRef:
  kind: Role
  name: openvas-discovery
  apiGroup: rbac.authorization.k8s.io
